### PR TITLE
VIH-8285 Right alignment on Leave consultation modal is not same as left

### PR DESCRIPTION
**Pull request by ZJianWang**
### JIRA link (if applicable) ###

VIH-8285

### Change description ###

image
**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by ibthmcts — APPROVED** [review]

**Review by FarronF — COMMENTED** [review]
Could you provide a screen shot?

**Comment by ZJianWang** [comment]
image

**Comment by ZJianWang** [comment]
> Could you provide a screen shot? One for small and one for large displays.

image

**Review by kevin-hmcts — APPROVED** [review]
LGTM

**Pull request merged**
