### PR TITLE
VIH-8671 - BookingsApi change required an update to TestApi and the dependencies…

### PR DESCRIPTION
**Pull request by MichaelKeaneathmcts**
… here needed to be updated.

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by kevin-hmcts — DISMISSED** [review]
LGTM

**Review by krishnapottekkat-hmcts — APPROVED** [review]
LGTM

**Comment by MichaelKeaneathmcts** [comment]
Changes made by Farron supersede this change.

**Pull request closed without merging**
