### PR TITLE
VIH-8063 removed nested header, promoted aria header role to parent header

### PR DESCRIPTION
**Pull request by omio-ma**
### JIRA link ###
https://tools.hmcts.net/jira/browse/VIH-8063

### Change description ###
- nested headers was causing the accessibility tests to fail

**Does this PR introduce a breaking change?**

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by alberto-hortiguela — APPROVED** [review]
LGTM

**Review by ZJianWang — APPROVED** [review]

**Review by MichaelKeaneathmcts — COMMENTED** [review]
I have to ask, does this affect any Acceptance testing?  Are there changes required and have they been done?

**Comment by omio-ma** [comment]
@MichaelKeaneathmcts this change is actually to fix some failing acceptance accessibility tests that has started to fail because we have nested headers and the nested header having the aria label of "banner" as opposed to having the parent header.

**Comment by omio-ma** [comment]
it should fix this test for instance: HearingRoomPageAccessibility

Pipeline running this test:
https://hmctsreform.visualstudio.com/VirtualHearings/_build/results?buildId=35659&view=ms.vss-test-web.build-test-results-tab&runId=1151278&resultId=100153&paneView=debug

**Pull request merged**
