### PR TITLE
VIH-8111 Fix the video alignment is slide to left

### PR DESCRIPTION
**Pull request by ZJianWang**
### JIRA link (if applicable) ###

VIH-8111

### Change description ###
image

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by alberto-hortiguela — APPROVED** [review]
LGTM

**Comment by abiodunoke** [comment]
Looks good and aligned with current preprod. Thanks

**Review by FarronF — CHANGES_REQUESTED** [review]
Where is the mic visualizer? Shouldn't that be below the self view video?

**Comment by AWildBugAppeared** [comment]
I think this will conflict with my changes for the mic visualizer that Farron mentioned. Will call you about this

**Review by AWildBugAppeared — CHANGES_REQUESTED** [review]
I think this will conflict with my changes for the mic visualizer that Farron mentioned. Will call you about this

**Pull request closed without merging**
