### PR TITLE
VIH-9673 upgrade to NG 15

### PR DESCRIPTION
**Pull request by shaed-parkar**
### JIRA link (if applicable) ###

VIH-9673

### Change description ###

* Upgrade to NG 15
* Upgrade OIDC package and security service interface
* Breaking API changes due to package upgrades

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

### CODE REVIEW

**Review by will-craig — COMMENTED** [review]
There's a a circular dependency exception being thrown from the dependency injector, on this branch. 
image

**Review by phildebrah — APPROVED** [review]
Tested and working successfully

**Pull request merged**
