### PR TITLE
VIH-8607 - Video-web | All Users | Ambiguous form label (AA)

### PR DESCRIPTION
**Pull request by twyfordr273**
1. Added aria labels for people that are hard of seeing that will read out the case name when using text to speech

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by oliver-scott — DISMISSED** [review]

**Review by marcogagliardi — APPROVED** [review]
👌🏽

**Review by arellison — APPROVED** [review]
Looks good @twyfordr273

**Comment by oliver-scott** [comment]
could you reduce the indentation, for consistency? You might have the tab size in your editor set to 4

**Review by oliver-scott — DISMISSED** [review]

**Review by will-craig — APPROVED** [review]

**Review by RosDiaf — APPROVED** [review]

**Review by oliver-scott — APPROVED** [review]

**Comment by phillipjchambers** [comment]
Not essential, but it makes the templates much more readable if you put these kind of changes in the component.ts file, e.g., `getAriaLabel(hearing: Hearing): string`

**Review by phildebrah — APPROVED** [review]
Tested and working fine

**Pull request merged**
